"use client"

import { useRouter } from "next/navigation"
import { ArrowRight, Sparkles, Code2, Clock, Target, Users, ChevronRight, Bot, LaptopMinimalCheck } from "lucide-react"

export const FloatingIcons = () => (
    <>
        <div className="hidden lg:flex fixed left-6 top-1/3 -translate-y-1/2 text-teal-500 opacity-20 pointer-events-none">
            <Bot className="w-16 h-16 lg:w-24 lg:h-24 animate-bounce" />
        </div>
        <div className="fixed right-6 top-1/2 -translate-y-1/2 text-teal-500 opacity-20 pointer-events-none">
            <LaptopMinimalCheck className="w-24 h-24 animate-bounce" style={{ animationDelay: "0.5s" }} />
        </div>
    </>
);

const steps = [
  {
    number: "01",
    title: "Choose your domain",
    description: "Select from frontend, backend, AI, mobile, DevOps, and more.",
  },
  {
    number: "02",
    title: "Set your preferences",
    description: "Tell us your level, time available, tech stack, and goals.",
  },
  {
    number: "03",
    title: "Get tailored ideas",
    description: "Receive 3 handpicked project suggestions built around you.",
  },
]

const features = [
  {
    icon: <Sparkles className="w-5 h-5" />,
    title: "AI-powered suggestions",
    description: "Our LLM analyzes your profile and generates projects that actually match your skill level.",
  },
  {
    icon: <Code2 className="w-5 h-5" />,
    title: "Tech-stack aware",
    description: "Every suggestion uses only the technologies you selected — no irrelevant tools.",
  },
  {
    icon: <Clock className="w-5 h-5" />,
    title: "Time-scoped ideas",
    description: "From 2-hour prototypes to 3-month production apps, we match your schedule.",
  },
  {
    icon: <Target className="w-5 h-5" />,
    title: "Goal-oriented",
    description: "Whether you're building a portfolio piece or an MVP, we tailor the scope accordingly.",
  },
  {
    icon: <Users className="w-5 h-5" />,
    title: "Solo or team",
    description: "Projects are scoped for your collaboration style — solo, small team, or large group.",
  },
  {
    icon: <ChevronRight className="w-5 h-5" />,
    title: "10 domains covered",
    description: "Frontend, fullstack, backend, mobile, AI, data, IoT, desktop, DevOps, and cybersecurity.",
  },
]

const domains = [
  "Frontend Web", "Full-Stack", "Backend / API", "Mobile", "AI / ML",
  "Data Analytics", "IoT", "Desktop", "DevOps", "Cybersecurity",
]

export default function HomePage() {
  const router = useRouter()

  return (
    <main className="min-h-screen bg-white">
      <FloatingIcons/>

      <section className="relative overflow-hidden border-b border-gray-100">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_left,_#e6faf3_0%,_transparent_60%)]" />
        <div className="relative max-w-5xl mx-auto px-6 py-28 flex flex-col items-center text-center gap-8">
          <span className="inline-flex items-center gap-2 text-sm font-medium text-teal-700 bg-teal-50 border border-teal-200 rounded-full px-4 py-1.5">
            <Sparkles className="w-3.5 h-3.5" />
            AI-powered project discovery
          </span>

          <h1 className="text-5xl sm:text-6xl font-bold text-gray-900 leading-tight max-w-3xl">
            Never run out of{" "}
            <span className="text-teal-600">project ideas</span>{" "}
            again
          </h1>

          <p className="text-lg text-gray-500 max-w-xl leading-relaxed">
            Answer a few questions about your skills and goals. Get 3 tailored project suggestions
            generated by AI : ready to build, right now!
          </p>

          <div className="flex flex-col sm:flex-row gap-3 mt-2">
            <button
              onClick={() => router.push("/project-generator")}
              className="inline-flex items-center justify-center gap-2 bg-teal-500 hover:bg-teal-600 text-white font-semibold px-7 py-3.5 rounded-xl transition-colors text-sm"
            >
              Find my next project
              <ArrowRight className="w-4 h-4" />
            </button>
            <button
              onClick={() => router.push("/about")}
              className="inline-flex items-center justify-center gap-2 border border-gray-200 hover:border-gray-300 text-gray-700 hover:text-gray-900 font-medium px-7 py-3.5 rounded-xl transition-colors text-sm bg-white"
            >
              Learn more
            </button>
          </div>

          <div className="flex flex-wrap justify-center gap-2 mt-6 max-w-2xl">
            {domains.map((d) => (
              <span
                key={d}
                className="text-xs font-medium text-gray-500 bg-gray-50 border border-gray-200 rounded-full px-3 py-1"
              >
                {d}
              </span>
            ))}
          </div>
        </div>
      </section>

      <section className="max-w-5xl mx-auto px-6 py-24">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold text-gray-900 mb-3">How it works</h2>
          <p className="text-gray-500 max-w-md mx-auto">
            Three simple steps to go from blank page to a concrete project idea.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
          {steps.map((step, i) => (
            <div
              key={step.number}
              className="relative flex flex-col gap-4 p-7 rounded-2xl border border-gray-100 bg-white hover:border-teal-200 hover:shadow-sm transition-all"
            >

              {i < steps.length - 1 && (
                <div className="hidden sm:block absolute top-10 -right-3 w-6 h-px bg-gray-200 z-10" />
              )}
              <span className="text-4xl font-bold text-teal-100">{step.number}</span>
              <div>
                <h3 className="font-semibold text-gray-900 mb-1">{step.title}</h3>
                <p className="text-sm text-gray-500 leading-relaxed">{step.description}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="bg-gray-50 border-y border-gray-100">
        <div className="max-w-5xl mx-auto px-6 py-24">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-3">Built for developers</h2>
            <p className="text-gray-500 max-w-md mx-auto">
              Every suggestion is tailored to your exact profile!
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {features.map((f) => (
              <div
                key={f.title}
                className="flex flex-col gap-3 p-6 rounded-2xl bg-white border border-gray-100 hover:border-teal-200 transition-colors"
              >
                <div className="w-9 h-9 rounded-lg bg-teal-50 flex items-center justify-center text-teal-600">
                  {f.icon}
                </div>
                <div>
                  <h3 className="font-semibold text-gray-900 text-sm mb-1">{f.title}</h3>
                  <p className="text-sm text-gray-500 leading-relaxed">{f.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="max-w-5xl mx-auto px-6 py-24">
        <div className="relative overflow-hidden rounded-3xl bg-teal-500 px-10 py-16 text-center">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_bottom_right,_#0f766e_0%,_transparent_60%)]" />
          <div className="relative flex flex-col items-center gap-6">
            <h2 className="text-3xl font-bold text-white max-w-lg">
              Ready to build something great?
            </h2>
            <p className="text-teal-100 max-w-md">
              It takes less than 2 minutes to fill out the form and get your personalized project ideas.
            </p>
            <button
              onClick={() => router.push("/project-generator")}
              className="inline-flex items-center gap-2 bg-white text-teal-600 hover:bg-teal-50 font-semibold px-7 py-3.5 rounded-xl transition-colors text-sm"
            >
              Get started
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </section>

    </main>
  )
}